version: "3.8"

services:
  blogapp.api:
    image: ${DOCKER_REGISTRY-}blogappapi
    build:
      context: .
      dockerfile: src/BlogApp.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__BlogAppPostgreConnectionString: "Host=postgresdb;Port=5432;Database=${POSTGRES_DB:-BlogAppDb};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres};Pooling=true;Minimum Pool Size=10;Maximum Pool Size=200;Connection Idle Lifetime=300;Connection Pruning Interval=10;"
      ConnectionStrings__RedisCache: "redis_server:6379,abortConnect=false,connectTimeout=5000,syncTimeout=5000,connectRetry=3,keepAlive=60"
      RabbitMQOptions__HostName: rabbitmq
      RabbitMQOptions__UserName: ${RABBITMQ_DEFAULT_USER:-blogapp}
      RabbitMQOptions__Password: ${RABBITMQ_DEFAULT_PASS:-supersecret}
    depends_on:
      postgresdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis.cache:
        condition: service_started
    networks:
      - blogapp_net
    ports:
      - "8080:8080"
    restart: always

  postgresdb:
    container_name: postgresdb
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-BlogAppDb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=1GB"
      - "-c"
      - "work_mem=4MB"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - PGPASSWORD=$${POSTGRES_PASSWORD:-postgres} pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-BlogAppDb} -h localhost
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - blogapp_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-blogapp}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-supersecret}
    ports:
      - "15672:15672" # web arayüzü (isteğe bağlı)
      - "5672:5672"   # uygulama bağlantısı
    restart: always
    networks:
      - blogapp_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  redis.cache:
    image: redis:latest
    container_name: redis_server
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - blogapp_net

  seq:
    image: datalust/seq:latest
    container_name: seq_logs
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_ADMIN_PASSWORD:-Admin123!}
      BASE_URI: ${SEQ_BASE_URI:-http://localhost:5341}
    volumes:
      - seq_data:/data
    ports:
      - "5341:80"  # Seq web UI
    networks:
      - blogapp_net
      
volumes:
  postgres_data:
  redis_data:
  seq_data:

networks:
  blogapp_net:
    driver: bridge
